# Generated by Django 4.1.3 on 2022-11-24 09:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
